Test case for the process order function when there is a single stop loss order in the list of orders, and the stop price is reached
elys-network/trade-shield-contract pull request #6
Opened 2023-08-03 10:36 UTC by politeWall

this pull request is for resolving the issue [#190](https://github.com/elys-network/issues/issues/190)

2023-08-03 11:02 UTC, cosmic-vagabond commented on src/types/order/impls/new_dummy.rs
>              order_amount: coin(1000, "btc"),
@politeWall let change this example to make a more realistic scenario, lets assume that the user has 2 btc and wants to sell it to usdc when the stop price of btc against usdc reaches 20’000 usdc (1 btc = 20k usdc) how would you test that?

2023-08-04 08:27 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +            .init_balance(storage, &Addr::unchecked("user"), coins(150, "eth"))
that should be a USDC balance

2023-08-04 08:29 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +            &coins(1200, "btc"),
same here you are initiating the contract with an enormous btc amount in the contract wallet not sure why

2023-08-04 08:30 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +        200
why would the btc balance of the user be equal to 200, we were supposed to receive USDC when sold not BTC

2023-08-04 08:30 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +            .query_balance("user", "eth")
we want to check USDC balance

2023-08-04 09:31 UTC, cosmic-vagabond requested changes

2023-08-04 09:31 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +//  Bitcoin have a value of 20 000
@politeWall lets assume that the BTC value is at 30k at t(0) and at t(1) the price of BTC drops to 20k that when the stop loss order will be triggered to sell the order BTC amounts to USDC

2023-08-04 09:31 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +            .init_balance(storage, &Addr::unchecked("owner"), coins(2, "btc"))
here we assumed that the user already created the stop loss order with 2 BTC as the order amount that’s why we are allocated 2 BTC to the contract wallet

2023-08-04 09:31 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +        coin(20000, "usdc"),
I would assume this is the order price therefore the stoploss price, therefore this stop loss order will be triggered when the price of btc will hits 20k USDC mark

2023-08-04 09:31 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +        .unwrap();
@politeWall we dont know what is the price of BTC at this point

2023-08-04 09:31 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +    );
can you also test the user BTC balance

2023-08-04 16:42 UTC, cosmic-vagabond requested changes

2023-08-04 16:42 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +    mock_oracle(&mut service, values, &mut app, addr.clone());
@politeWall your test should still be focused on testing the process order flow but you can inject a mocked oracle service to be used by process order instead of the actual oracle service

2023-08-04 16:42 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +    );
@politeWall here we assume that the oracle price of BTC/USDC is 30k so therefore the order is not executed yet right? if so can you add another assert that makes sure that the order still exists?

2023-08-04 16:42 UTC, cosmic-vagabond commented on src/tests/process_order/successful_process_stop_loss_order.rs
> +    .unwrap()
@politeWall that should still live in the test scope

2023-08-08 15:43 UTC, cosmic-vagabond requested changes

2023-08-08 15:43 UTC, cosmic-vagabond commented on src/lib.rs
> +        //mod test disable cause it not compiling
@politeWall can you describe the issue here?

2023-08-08 15:43 UTC, cosmic-vagabond commented on src/tests/mock/oracle.rs
> +pub struct OracleMock {
@politeWall we want this structure to be only available in the test enviroment

2023-08-08 15:43 UTC, cosmic-vagabond commented on src/tests/mock/oracle.rs
> +        custom_query_type: PhantomData,
@politeWall whats the difference between `OracleMockWithQuerier` and `OracleMock`?

2023-08-08 15:43 UTC, cosmic-vagabond commented on src/tests/mock/test.rs
> +    assert_eq!(get_all_prices_response.prices[1].amount, prices[1].amount);
@politeWall whats the output of this test?

2023-08-08 15:49 UTC, politeWall commented on src/tests/mock/test.rs
> +    assert_eq!(get_all_prices_response.prices[1].amount, prices[1].amount);
The test isn't compiling, so there's no output. Its purpose is to testing of the mocking of the oracle module

2023-08-08 15:50 UTC, politeWall commented on src/tests/mock/oracle.rs
> +pub struct OracleMock {
i will take care of that

2023-08-08 15:54 UTC, politeWall commented on src/tests/mock/oracle.rs
> +        custom_query_type: PhantomData,
_OracleMockWithQuerier_ contain the all the Mocking from the original _MockQuerier_ with the custom query output from _OracleMock_

2023-08-08 16:00 UTC, politeWall commented on src/lib.rs
> +        //mod test disable cause it not compiling
Because the code you observed in src/tests/mock/test.rs is not compiling, I have excluded this portion of the code from compilation to prevent it from disrupting the rest of the test code.

2023-08-08 16:13 UTC, cosmic-vagabond commented on src/lib.rs
> +        //mod test disable cause it not compiling
sure but I guess my question is why it is causing an error?

2023-08-08 16:46 UTC, cosmic-vagabond commented on src/tests/mock/oracle.rs
> +        custom_query_type: PhantomData,
I dont understand when should I use one or the other?

2023-08-08 16:47 UTC, cosmic-vagabond commented on src/tests/mock/test.rs
> +    assert_eq!(get_all_prices_response.prices[1].amount, prices[1].amount);
whats the error you are getting?

2023-08-10 16:38 UTC, cosmic-vagabond requested changes

2023-08-10 16:38 UTC, cosmic-vagabond commented on src/tests/elys_oracle/querier.rs
> +}
@politeWall if that file is meant to contain only the Oracle querier struct why it is called `ElysQuerier`?

2023-08-11 09:05 UTC, politeWall commented on src/tests/elys_oracle/querier.rs
> +}
its not how we should call it ?

2023-08-15 14:41 UTC, cosmic-vagabond approved these changes
LGTM

2023-08-15 14:41 UTC, merged